### PR TITLE
Fix regex parser being to greedy with partial string patterns

### LINKED ISSUE #18: Different parsing allignment behaviour between 0.2.* and 0.3.*
Trying to parse parts of a filename and store the remainder in the last part. The remaining parts are alligned differently between versions.

The following code illustrates the problem:
```
import trollsift

fname = 'Amplitude_VH_db_S1A_IW_GRDH_1SDV_20160528T171628_20160528T171653_011462_011752_0EED.tif'
template_parts = ['{band_type}',
                  '{polarization_extracted}',
                  '{unit}',
                  '{s1_fname}']
template = '_'.join(template_parts)
p = trollsift.Parser(template)

print(p.parse(fname))
```
**Version 0.2.1**
`{'s1_fname': 'S1A_IW_GRDH_1SDV_20160528T171628_20160528T171653_011462_011752_0EED.tif', 'unit': 'db', 'polarization_extracted': 'VH', 'band_type': 'Amplitude'}`

**Version 0.3.1**
`{'band_type': 'Amplitude_VH_db_S1A_IW_GRDH_1SDV_20160528T171628_20160528T171653', 'polarization_extracted': '011462', 'unit': '011752', 's1_fname': '0EED.tif'}`

It seems like the direction of parsing has changed, thus producing inconsistent results. Is there a possible solution/workaround to get the old alignment direction in version 0.3.*?
Thanks in advance.

### PR DESCRIPTION
**Pull request by djhoese**
Closes #18 created by @egremmer.

This modifies the default fallback pattern to be non-greedy so it doesn't pull in *everything*.

I *think* this should work, but @pnuu and @mraspaud may want to compare this against some of their use cases in Satpy or trollflow2 type stuff. Normally in Satpy I think we have fully specified patterns.

TODO:

- [x] I need to analyze this when the user specifies other wildcard file patterns like `{band_type:s}` since this currently fails. This will very likely break Satpy patterns if I fix this. Need to test.

### CODE REVIEW

**Comment by djhoese** [comment]
Ok nevermind, most recent commit makes this work. I'm still worried about Satpy breakage.

**Comment by djhoese** [comment]
Ok. Do you think using the term "greedy" and talking about patterns matching the shortest string is a good enough explanation? Where do you think it should be documented?

**Comment by mraspaud** [comment]
The usage section will be well suited for this. Maybe put a new paragraph in the end with some examples or implementation notes ? The explanation you propose is good, especially if you provide the example discussed here as illustration.

**Comment by djhoese** [comment]
Documentation added. Let me know if it makes sense and/or if you think I should mention this somewhere else in the docs. I also added intersphinx so I could link to the python docs and fixed some old python 2 style print statements.

**Pull request merged**
